### ISSUE TITLE
OperationalError at /new

### ISSUE THREAD

**Issue by mifo123** [guchem/calculator#1]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">OperationalError at /new</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">no such table: core_history</pre>

Request Method: | POST
-- | --
http://127.0.0.1:8000/new
3.2.6
OperationalError
no such table: core_history
/home/mifo/interview/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py, line 423, in execute
/home/mifo/interview/venv/bin/python
3.8.10
['/home/mifo/interview/calulator',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/mifo/interview/venv/lib/python3.8/site-packages']
Tue, 24 Aug 2021 09:18:23 +0000

</body>
</html>

![image](https://user-images.githubusercontent.com/19674506/130591759-6a0b0554-4fe7-4275-831d-bc5e21659f5e.png)

**Comment by guchem** [comment]
it is a migration issue not a bug
run the following commands
python manage.py makemigrations core
python manage.py migrate
